#!/bin/bash

wid=$(xdotool search --classname urxvtq)

if [ -z "$wid" ]; then
  urxvtc -name urxvtq -geometry 113x20
  wid=$(xdotool search --classname urxvtq)
  xdotool windowfocus $wid
  xdotool key Control_L+l
elif [ -z "$(xdotool search --onlyvisible --classname urxvtq 2>/dev/null)" ]; then
  xdotool windowmap $wid
  xdotool windowfocus $wid
else
  xdotool windowunmap $wid
fi
